Repository PeanutCoffee/DSA, pull requests merged in 2022-10, with the labels that each got.

#11 Reverse Vowels LeetCode 345(Easy)
  Python/ReverseVowels.py
Labels: hacktoberfest-accepted

#12 Count Zero in a number
  Java/CountZeroes.java
Labels: hacktoberfest-accepted

#16 Added 4x1 Multiplexer
  Verilog - Hardware Language/4x1.v
Labels: hacktoberfest-accepted

#17 Binary Search code In C++ #15
  C++/BinarySearch.CPP
Labels: hacktoberfest-accepted

#18 Added Counter and its Testbench
  Verilog - Hardware Language/counter.v
  Verilog - Hardware Language/counter_tb.v
Labels: hacktoberfest-accepted

#21 Create fsm.v
  Verilog - Hardware Language/fsm.v
Labels: hacktoberfest-accepted

#29 Hierarchical Inheritance
  C++/heirarchical_inheritance.cpp
Labels: hacktoberfest-accepted

#32 fixes #22
  C++/MultiStageGraph.cpp
Labels: hacktoberfest-accepted

#27 Bubble Sort Algorithm in c++
  C++/bublesort.cpp
Labels: hacktoberfest-accepted

#43 Kth smallest element in a BST
  C++/KthSmallestInBST.cpp
Labels: hacktoberfest-accepted

#48 DestinationCity LeetCode Problem
  C++/DestinationCity.cpp
Labels: hacktoberfest-accepted

#46 Selection Sort in cpp
  C++/Selection Sort.cpp
Labels: hacktoberfest-accepted

#62 added lc987 solution
  C++/Maximum Sum BST in Binary Tree.cpp
  C++/VerticalOrderTraversalBinaryTree.cpp
Labels: hacktoberfest-accepted

#56 LeetCode 217. Contains Duplicate
  Python/ContainsDuplicates.py
  Python/Readme.md
  Python/ReverseLinkedList.py
  Python/RotateImage.py
Labels: hacktoberfest-accepted

#63 Issue: Container with Most Water Leetcode 11 (Medium)
  Python/container_with_most_water.py
Labels: hacktoberfest-accepted

#66 LC 336
  Java/Palindrome Pairs.java
  Python/Substring with Concatenation of All Words.py
Labels: hacktoberfest-accepted

#57 Added Binary Tree Codes in C++
  Binary Tree/Binary Tree.cpp
  Binary Tree/Check For Height Balanced BT.cpp
  Binary Tree/Children Sum Property.cpp
  Binary Tree/Construct BT from InOrder and PreOrder.cpp
  Binary Tree/Construct BT from InOrder and PreOrder.exe
  Binary Tree/Convert BT to DLL.cpp
  Binary Tree/Height of BT.cpp
  Binary Tree/In Order Traversal.cpp
  Binary Tree/Level Order Traversal Line by Line Part 1.cpp
  Binary Tree/Level Order Traversal Line by Line Part 2.cpp
  Binary Tree/Level Order Traversal.cpp
  Binary Tree/Maximum Width of BT.cpp
  Binary Tree/Maximum in BT.cpp
  Binary Tree/Post Order Traversal.cpp
  Binary Tree/Pre Order Traversal.cpp
  Binary Tree/Print Left View of BT.cpp
  Binary Tree/Print Nodes at K Distance.cpp
  Binary Tree/Size of BT.cpp
Labels: hacktoberfest-accepted

#55 Adding Sorting Algorithms in Python
  Python/bubble_sort.py
  Python/insertion_sort.py
  Python/selection_sort.py
Labels: hacktoberfest-accepted

#72 lc1402
  C++/Reducing Dishes.cpp
Labels: hacktoberfest-accepted

#54 Discord bot
  Python/Bot/orionbot.py
  Python/Bot/orionflask.py
Labels: hacktoberfest-accepted

#73 Create Search_an_element_in_a_sorted_and_rotated_Array.cpp
  C++/Search_an_element_in_a_sorted_and_rotated_Array.cpp
Labels: hacktoberfest-accepted

#77 Update
  InterviewPrep/Concepts.md
  Java/Readme.md
Labels: hacktoberfest-accepted

#53 Added BubbleSortInCpp
  C++/BubbleSort.cpp
Labels: hacktoberfest-accepted

#81 Added Trapping Rain Water
  InterviewPrep/Trapping Rain Water.cpp
Labels: hacktoberfest-accepted

#80 Overleaf
  software-engineer-resume.pdf
Labels: hacktoberfest-accepted

#106 Impliment Quick Sort in C++
  C++/QuickSort.cpp
Labels: hacktoberfest-accepted

#98 House Robber LeetCode 198
  C++/House Robber LC198.cpp
Labels: hacktoberfest-accepted

#101 Issue: Leetcode 567- Permutation in String
  Python/permutation_in_string.py
Labels: hacktoberfest-accepted

#94 atoi implementation
  C++/String to Integer (atoi) .cpp
Labels: hacktoberfest-accepted

#90 Added Important Concepts
  InterviewPrep/2stack.cpp
  InterviewPrep/DFS.cpp
  InterviewPrep/arrins.c
  InterviewPrep/bubblesort.c
  InterviewPrep/heapsort.cpp
Labels: hacktoberfest-accepted

#85 Sorting Algorithms complexities
  Sorting_algorithm_comparison.jpg
Labels: hacktoberfest-accepted

#52 Create Spiral Matix.cpp
  C++/Spiral Matix.cpp
Labels: hacktoberfest-accepted

#105 fixes issue #103
  C++/minCoinChange.cpp
Labels: hacktoberfest-accepted

#107 Added kadane algorithm in java
  Java/kadanealgo.java
Labels: hacktoberfest-accepted

#96 sort-added
  Sorting/bubble.py
  Sorting/counting.py
  Sorting/insertion.py
  Sorting/merge.py
  Sorting/quick.py
  Sorting/selection.py
  Sorting/sort.md
Labels: hacktoberfest-accepted

#75 add sudoku solver
  C++/Sudoku solver.cpp
Labels: hacktoberfest-accepted

#68 Added Second Largest Number in C++
  C++/second_largest.cpp
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#58 fixes #44
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#40 fixes#31
  Java/BinaryTreeInorderTraveral.java
Labels: hacktoberfest-accepted

#111 Added Company Questions
  InterviewPrep/Google Questions.pdf
  InterviewPrep/Meta Placement Questions.pdf
Labels: hacktoberfest-accepted

#115 Check if the linked list is palindrome or not
  Graphs/keysAndRooms.cpp
  Linked List/palindromeLinkedList.cpp
Labels: hacktoberfest-accepted

#118 Number of Islands
  Graphs/numberIslands.cpp
Labels: hacktoberfest-accepted

#123 Longest Substring Without Repeating Characters
  Sliding Window/longestSubstringChar.cpp
Labels: hacktoberfest-accepted

#130 Issue: LC 424: Longest Repeating Character Replacement
  Python/longest_repeating_character_replacement.py
Labels: hacktoberfest-accepted

#102 Add ChristmasTree.java and MaxElement.java
  Java/ChristmasTree.java
  Java/MaxElement.java
Labels: hacktoberfest-accepted

#121 Create Longest_Common_Subsequence.cpp
  C++/Longest_Common_Subsequence.cpp
Labels: hacktoberfest-accepted

#127 Jump Game
  Dynamic Programming/jumpGame.cpp
Labels: hacktoberfest-accepted

#126 Fibonacci Number
  Dynamic Programming/fibonacciNumber.cpp
Labels: hacktoberfest-accepted

#142 Updated with changes
  C++/kadanes.cpp
  Python/selection_sort.py
Labels: hacktoberfest-accepted

#140 Stock Span in CPP
  C++/Stock Span.cpp
Labels: hacktoberfest-accepted

#138 0-1 Knapsack Problem
  C++/0-1 KnapSack.cpp
Labels: hacktoberfest-accepted

#137 Issue : Leetcode 15 - 3Sum
  Python/three_sum.py
Labels: hacktoberfest-accepted

#110 Create Minimum_Height_Trees.cpp
  C++/Minimum_Height_Trees.cpp
Labels: hacktoberfest-accepted

#23 Created bubble sort in python3
  Python/bubbleSort.py
Labels: hacktoberfest-accepted

#147 Added Important Concepts
  InterviewPrep/dfsnbfs.cpp
  InterviewPrep/heapsort.cpp
  InterviewPrep/infixtopostfix.cpp
  InterviewPrep/mstbyprims.cpp
  InterviewPrep/queueusingarray.cpp
  InterviewPrep/queueusinglinkedlist.cpp
  InterviewPrep/removeduplicatefromlinkedlist.cpp
Labels: hacktoberfest-accepted

#151 Dynamic_memory_allocation in cpp
  C++/3_Dynamic_Allocation.cpp
Labels: hacktoberfest-accepted

#128 creadted DP folder also added three java code files in it
  Dynamic Programming/0-1 Knapsack Problem.java
  Dynamic Programming/Count number of hops.java
  Dynamic Programming/Longest Increasing Subsequence (LIS).java
Labels: hacktoberfest-accepted

#153 fixed issue #152
  C++/BinaryCoefficient.cpp
Labels: hacktoberfest-accepted

#156 fixed issue #153
  C++/MCM.cpp
Labels: hacktoberfest-accepted

#157 Added MATLAB codes
  MATLAB Codes/exp5.m
  MATLAB Codes/exp6.m
  MATLAB Codes/exp7.m
  MATLAB Codes/exp8.m
  MATLAB Codes/exp9.m
  MATLAB Codes/rain.mp3
  MATLAB Codes/sing.wav
  MATLAB Codes/temp.m
Labels: hacktoberfest-accepted

#160 Pascal Triangle dynamic programming problem solution in python
  CONTRIBUTING.md
  Dynamic Programming/Python/Pascal's Triangle/README.md
  Dynamic Programming/Python/Pascal's Triangle/pascal.py
Labels: hacktoberfest-accepted

#162 prism's algo in cpp
  C++/prism_algo.cpp
Labels: hacktoberfest-accepted

#167 Coin change dynamic programming solution in python
  Dynamic Programming/Python/Coin Change/README.md
  Dynamic Programming/Python/Coin Change/coin_change.py
Labels: hacktoberfest-accepted

#165 Fixed spelling error (prism -> prim's) & added a parentheses balancing code using cpp
  C++/balance_parentheses.cpp
  C++/prims_algo.cpp
Labels: hacktoberfest-accepted

#175 Add files via upload
  Python/LinearRegressionFromScratch.ipynb
Labels: hacktoberfest-accepted

#163 Huffman Coding in C++ Added
  C++/huffman.cpp
Labels: hacktoberfest-accepted

#174 Added BFS and DFS in C++
  C++/Graphs/Breadth_first_search.cpp
  C++/Graphs/Depth_first_search.cpp
Labels: hacktoberfest-accepted

#41 C++ Programs on Array and Searching Algorithms #hacktoberfest
  C++/2DArraySearch.CPP
  C++/Array.CPP
  C++/ArrayMinMax.CPP
  C++/Arrayinsertion.CPP
  C++/Arraypointer.cpp
  C++/BubbleSort.CPP
  C++/MaxROtationArri.cpp
  C++/arrayshiftbyone.cpp
  C++/boubleSort.cpp
  C++/count_number_of_sentence.cpp
  C++/cylinder-rotate-array.cpp
  C++/demo.cpp
  C++/max-sum-rotation.cpp
  C++/maxArray.CPP
Labels: hacktoberfest-accepted

#178 Stack and Dynamic Stack
  Java/DynamicStack.java
  Java/Stack.java
Labels: hacktoberfest-accepted

#177 Lazy_queries_segment_tree.cpp
  C++/Lazy_queries_segment_tree.cpp
Labels: hacktoberfest-accepted

#180 MergeSort using Recursion
  Java/MergeSort.java
Labels: hacktoberfest-accepted

#182 Intersection in between 2 linked-list
  C++/Linked List/intersection in a linkedlist.cpp
  C++/Linked List/rotate a linkedlist.cpp
Labels: hacktoberfest-accepted

#135 Created Euclidean.java
  Java/Euclidean.java
Labels: hacktoberfest-accepted

#185 Linear Regression model
  ML Algorithms/Linear Regression/Linear Regression model.ipynb
  ML Algorithms/Linear Regression/Symbolic_regression_classification_generator.py
  ML Algorithms/Linear Regression/Toyota.csv
  ML Algorithms/Readme.md
Labels: good first issue, hacktoberfest-accepted

#187 Decision Tree
  ML Algorithms/Decision Tree/Churn.csv
  ML Algorithms/Decision Tree/Decision Tree.ipynb
  ML Algorithms/Decision Tree/Iris.csv
  ML Algorithms/Decision Tree/test.txt
  ML Algorithms/Decision Tree/titanic.csv
  ML Algorithms/Decision Tree/train.txt
  ML Algorithms/Decision Tree/vehicle.csv
  ML Algorithms/Decision Tree/winequalityN.csv
Labels: hacktoberfest-accepted

#189 Gradient Descent
  ML Algorithms/Gradient Descent/Churn.csv
  ML Algorithms/Gradient Descent/Gradient Descent.ipynb
  ML Algorithms/Gradient Descent/Iris.csv
Labels: hacktoberfest-accepted

#191 Clustering
  ML Algorithms/Clustering/Clustering.ipynb
  ML Algorithms/Clustering/Iris.csv
  ML Algorithms/Clustering/Mall_Customer.csv
  ML Algorithms/Clustering/desktop.ini
Labels: hacktoberfest-accepted

#200 Polymorphism in C++
  C++/polymorphism.cpp
Labels: hacktoberfest-accepted

#198 Issue: Leetcode:121 - Best Time to Buy and Sell Stock
  Python/best_time_to_buy_and_sell_stock.py
Labels: hacktoberfest-accepted

#195 Created Union Find algorithm in Java
  Java/SegmentTrees.java
  Java/UnionFind.java
Labels: hacktoberfest-accepted

#202 Added MATLAB Codes
  C++/BubbleSort.cpp
  MATLAB Codes/BodeA.m
  MATLAB Codes/BodeB.m
  MATLAB Codes/DFT.m
  MATLAB Codes/DSPPRACTICAL.m
  MATLAB Codes/DTFT.m
  MATLAB Codes/EMT1.m
  MATLAB Codes/EMT2.m
  MATLAB Codes/EMT3.m
  MATLAB Codes/EMT4.m
  MATLAB Codes/EXP1StepResB.m
  MATLAB Codes/EXP1StepResC.m
  MATLAB Codes/EXP2RootLocusA.m
  MATLAB Codes/EXPRootLocusC.m
  MATLAB Codes/EXPRootLucusB.m
  MATLAB Codes/Exp1StepResA.m
  MATLAB Codes/NyquistB.m
  MATLAB Codes/NyquistCi.m
  MATLAB Codes/NyquistCii.m
  MATLAB Codes/NyquistCiii.m
  MATLAB Codes/NyquistCiv.m
  MATLAB Codes/Nyquista.m
  MATLAB Codes/Ztransform.m
  MATLAB Codes/exp1.m
  MATLAB Codes/exp10.m
  MATLAB Codes/exp11.m
  MATLAB Codes/exp12.m
  MATLAB Codes/exp2.mlx
  MATLAB Codes/exp2a.m
  MATLAB Codes/exp2b.m
  MATLAB Codes/exp3.m
  MATLAB Codes/exp3b.m
  MATLAB Codes/exp4a.m
  MATLAB Codes/exp4b.m
  MATLAB Codes/exp5.m
  MATLAB Codes/exp6.m
  MATLAB Codes/exp7.m
  MATLAB Codes/exp8.m
  MATLAB Codes/exp9.m
  MATLAB Codes/value.m
  MATLAB Codes/yash_exp1.mlx
  MATLAB Codes/yash_probability.m
  MATLAB Codes/yash_sinc_spectrum.m
Labels: hacktoberfest-accepted

#207 Adobe Uber Walmart Atlassian Questions
  InterviewPrep/Adobe Uber Walmart Atlassian Questions.pdf
Labels: hacktoberfest-accepted

#206 Added Array questions in Interview Prep
  InterviewPrep/DuplicateZeroes.cpp
  InterviewPrep/MergeSortedArray.cpp
  InterviewPrep/RemoveDuplicateFromSortedArray.cpp
  InterviewPrep/RemoveElement.cpp
Labels: hacktoberfest-accepted

#230 Created StringTechniques in Java
  Java/StringTechniques.java
Labels: enhancement, hacktoberfest-accepted

#219 Sorting Algorithms in Rust
  Rust/Sorting/bubble_sort.rs
  Rust/Sorting/insertion_sort.rs
Labels: hacktoberfest-accepted

#226 Created Linked List in Java
  Java/LinkedList.java
Labels: enhancement, hacktoberfest-accepted

#228 Created BinaryTree in Java
  Java/BinaryTree.java
Labels: enhancement

#222 Added C programs
  C/VariadicFunctions.c
  C/postTransition.c
  C/queryingTheDocument.c
  C/smallTrianglesLargeTriangles.c
  C/sortingArrayOfStrings.c
  C/structuringTheDocument.c
Labels: enhancement

#204 AmstrongNumber_Checking.java
  Java/AmstrongNumber_Checking.java
Labels: enhancement, hacktoberfest-accepted

#242 Add files via upload
  Python/Radix Sort.py
Labels: enhancement

#243 Two Sum
  Java/Leetcode Problems/1-two-sum/1-two-sum.java
  Java/Leetcode Problems/1-two-sum/NOTES.md
  Java/Leetcode Problems/1-two-sum/README.md
  Java/Leetcode Problems/Readme.md
Labels: enhancement

#244 longest substring without repeating characters
  Java/Leetcode Problems/3-longest-substring-without-repeating-characters/3-longest-substring-without-repeating-characters.java
  Java/Leetcode Problems/3-longest-substring-without-repeating-characters/NOTES.md
Labels: enhancement

#245 median of two sorted arrays
  Java/Leetcode Problems/4-median-of-two-sorted-arrays/4-median-of-two-sorted-arrays.java
  Java/Leetcode Problems/4-median-of-two-sorted-arrays/NOTES.md
  Java/Leetcode Problems/4-median-of-two-sorted-arrays/README.md
Labels: enhancement

#246 container with most water
  Java/Leetcode Problems/11-container-with-most-water/11-container-with-most-water.java
  Java/Leetcode Problems/11-container-with-most-water/NOTES.md
  Java/Leetcode Problems/11-container-with-most-water/README.md
Labels: enhancement

#247 three sum and roman to integer
  Java/Leetcode Problems/13-roman-to-integer/13-roman-to-integer.java
  Java/Leetcode Problems/13-roman-to-integer/NOTES.md
  Java/Leetcode Problems/13-roman-to-integer/README.md
  Java/Leetcode Problems/15-3sum/15-3sum.java
  Java/Leetcode Problems/15-3sum/NOTES.md
  Java/Leetcode Problems/15-3sum/README.md
Labels: enhancement

#248 four sum
  Java/Leetcode Problems/18-4sum/0018-4sum.java
  Java/Leetcode Problems/18-4sum/NOTES.md
  Java/Leetcode Problems/18-4sum/README.md
Labels: enhancement

#249 remove-nth-node-from-end-of-list
  Java/Leetcode Problems/19-remove-nth-node-from-end-of-list/19-remove-nth-node-from-end-of-list.java
  Java/Leetcode Problems/19-remove-nth-node-from-end-of-list/NOTES.md
  Java/Leetcode Problems/19-remove-nth-node-from-end-of-list/README.md
Labels: enhancement

#252 generate parentheses
  Java/Leetcode Problems/22-generate-parentheses/22-generate-parentheses.java
  Java/Leetcode Problems/22-generate-parentheses/NOTES.md
  Java/Leetcode Problems/22-generate-parentheses/README.md
Labels: enhancement
